### ISSUE TITLE
biedronka

### ISSUE THREAD

**Issue by guamencja** [ProgramistaZpolski/nougat-max#18]
biedronka

**Comment by piotrbadelek** [comment]
Będzie też nowa wersja zabijsiedb

**Comment by piotrbadelek** [comment]
taki sklep robimy, można rzeczy wystawiać i kupować

**Comment by ProgramistaZpolski** [comment]
można rzeczy wystawiac i kupowac

**Comment by ProgramistaZpolski** [comment]
pytania jakieś?

**Comment by piotrbadelek** [comment]
dlaczego pan usuwa moje śmieci

czy jakieś pytania są na temat biedronki?

**Comment by piotrbadelek** [comment]
#20 nowe zabijsiędb 1.2
dodano komende find
szuka ona tekstu
i outputuje linijke na ktorej jest tekst
