### ISSUE TITLE
Luka 001 Codename "Kradież"

### ISSUE THREAD

**Issue by piotrbadelek** [ProgramistaZpolski/nougat-max#33]
Można sobie dodać pieniądze
jeszcze nie zdiagnozowana
wiemy że 300346870574612491 ja znalazl

edit 13:26, 15 maj:
prawdobodobnie coś z *zakup

**Comment by guamencja** [comment]
powodzenia w znalezieniu xd

**Comment by piotrbadelek** [comment]
podejrzewamy że to może być coś z *zakup

**Comment by guamencja** [comment]
👌

**Comment by piotrbadelek** [comment]
aha, czyli jesteśmy na tropie?

**Comment by guamencja** [comment]
może

**Comment by piotrbadelek** [comment]
czy to ma związek z biedronką?

**Comment by guamencja** [comment]
ale po co ty sie mnie pytasz, jak i tak ci konkretnie nie powiem XD

**Comment by piotrbadelek** [comment]
> ale po co ty sie mnie pytasz, jak i tak ci konkretnie nie powiem XD

"konkretnie" czyli możesz nas naprowadzić, ale nie powiesz dokładnie gdzie jest luka
